### ISSUE TITLE
PLSQL连我的服务器

### ISSUE THREAD

**Issue by jnuc093** [GentlHo/study#1]
PLSQL连我的服务器

**Comment by GentlHo** [comment]
收到

**Comment by jnuc093** [comment]
回复不要写没有意义的日志，练习下gist存放日志。

**Comment by jnuc093** [comment]
https://gist.github.com/jnuc093/1306c7960762e2cb68659afee6588c2e

**Comment by jnuc093** [comment]
git.oschina.net 速度比较快

**Comment by jnuc093** [comment]
JPA建立 one--to--one relationship？
